---
# source: https://magpi.raspberrypi.org/articles/pi-zero-w-smart-usb-flash-drive

# ensure mounted boot
- name: mount boot
  ansible.posix.mount:
    path: /boot
    state: mounted
    src: /dev/mmcblk0p1
    fstype: vfat
  changed_when: false

- name: enable usb driver in config.txt
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^dtoverlay=dwc2'
    line: dtoverlay=dwc2
  notify: reboot required

- name: automatically load module
  ansible.builtin.lineinfile:
    path: /etc/modules
    regexp: '^dwc2'
    line: dwc2
  notify: reboot required

- name: set usb_share_file variable
  ansible.builtin.set_fact:
    share_file: "{{ usb_share_file }}"

- name: "check if {{ usb_share_file }} file exists"
  ansible.builtin.stat:
    path: "{{ share_file }}"
  register: share_file_check

- name: "create {{ usb_share_file }} file with {{ usb_share_space }} size"
  ansible.builtin.command: fallocate -l {{ usb_share_space }} {{ usb_share_file }}
  when: not share_file_check.stat.exists

- name: "format the {{ usb_share_file }} file to fat32"
  ansible.builtin.command: mkdosfs {{ usb_share_file }} -F 32 -I -n WIFI-USB
  when: not share_file_check.stat.exists

- name: "ensure {{ usb_share_file }} mount"
  ansible.posix.mount:
    path: "{{ usb_share_path }}"
    src: "{{ usb_share_file }}"
    fstype: vfat
    opts: users,umask=000
    state: mounted

- name: ensure pip3 is installed
  ansible.builtin.package:
    name: python3-pip
    state: present

# this is somehow not working ... installing manually works ?!?
# - name: install watchdog python3 lib
#   ansible.builtin.pip:
#     name: watchdog
#     executable: pip3

- name: ensuring watchdog folder
  ansible.builtin.file:
    state: directory
    path: "{{ usb_share_watchdog_path }}"
    owner: root
    group: root
    mode: 0755

- name: deploy watchdog script
  ansible.builtin.template:
    src: usb_share_watchdog.py.jinja2
    dest: "{{ usb_share_watchdog_path }}/usb_share_watchdog.py"
    owner: root
    group: root
    mode: '0755'

- name: deploy watchdog systemd service unit
  ansible.builtin.template:
    src: usb_share_watchdog.service.jinja2
    dest: /etc/systemd/system/usb_share_watchdog.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

- name: enable and start the usb_share_watchdog.service
  ansible.builtin.systemd:
    name: usb_share_watchdog.service
    enabled: true
    state: started
