---
# source: https://magpi.raspberrypi.org/articles/pi-zero-w-smart-usb-flash-drive

# ensure mounted boot
- name: Override config.txt location for Raspberry Pi OS version before bookworm
  ansible.builtin.set_fact:
    rpi_wifi_usb_config_dir: /boot
  when: ansible_distribution_major_version | int < 12

- name: Mount boot
  ansible.posix.mount:
    path: "{{ rpi_wifi_usb_config_dir }}"
    state: mounted
    src: "{{ raspberry_pi_boot_dev }}"
    fstype: vfat
  changed_when: false

- name: Enable usb driver in config.txt
  ansible.builtin.lineinfile:
    path: "{{ rpi_wifi_usb_config_dir }}/config.txt"
    regexp: "^dtoverlay=dwc2"
    line: dtoverlay=dwc2
  notify: Reboot required

- name: Automatically load module
  ansible.builtin.lineinfile:
    path: /etc/modules
    regexp: "^dwc2"
    line: dwc2
  notify: Reboot required

- name: Set usb_share_file variable
  ansible.builtin.set_fact:
    share_file: "{{ usb_share_file }}"

- name: "Check if file exists: {{ usb_share_file }}"
  ansible.builtin.stat:
    path: "{{ share_file }}"
  register: share_file_check

- name: "Create the file with size {{ usb_share_space }}"
  ansible.builtin.command: fallocate -l {{ usb_share_space }} {{ usb_share_file }}
  when: not share_file_check.stat.exists
  changed_when: true

- name: "Format the file to fat32: {{ usb_share_file }}"
  ansible.builtin.command: mkdosfs {{ usb_share_file }} -F 32 -I -n WIFI-USB
  when: not share_file_check.stat.exists
  changed_when: true

- name: "Ensure mount {{ usb_share_file }}"
  ansible.posix.mount:
    path: "{{ usb_share_path }}"
    src: "{{ usb_share_file }}"
    fstype: vfat
    opts: users,umask=000
    state: mounted

- name: Ensure python3 is fully installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-full
    - python3-virtualenv

- name: Install watchdog python library
  ansible.builtin.pip:
    name:
      - watchdog
    virtualenv: "{{ usb_share_watchdog_path }}/venv"
  notify: Restart usb watchdog

- name: Ensuring watchdog folder
  ansible.builtin.file:
    state: directory
    path: "{{ usb_share_watchdog_path }}"
    owner: root
    group: root
    mode: "0755"
  notify: Restart usb watchdog

- name: Deploy watchdog script
  ansible.builtin.template:
    src: usb_share_watchdog.py.jinja2
    dest: "{{ usb_share_watchdog_path }}/usb_share_watchdog.py"
    owner: root
    group: root
    mode: "0755"
  notify: Restart usb watchdog

- name: Deploy watchdog systemd service unit
  ansible.builtin.template:
    src: usb_share_watchdog.service.jinja2
    dest: /etc/systemd/system/usb_share_watchdog.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd
